### ISSUE TITLE
Contact info 

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/user_research#20]
**Deliverable this task is associated with**

_See Deliverables tab here: _ https://docs.google.com/spreadsheets/d/1t3qTjQHkghSZqb1Bvaq6NGRzyeNXHonTaZredBtoo-M/edit#gid=0

- [Add the Deliverable #]

**RACI**

_Tag people in their roles_
- Responsible:
- Accountable:
- Consulted:
- Informed:

**Describe the the task**
- [ ] Add a more obvious help/contact us to contact us drop-down; previously discussed a modal w/ an email submission form

**Criteria for completion**
- Contact avenue added to sites 

**Estimate people time**
- [Hours or days of people time. 1 person, 4 hours]

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by mslarae13** [comment]
Quick link to https://microbiomedata.org/contact/ on the submission portal. 
Next / later, or prioritize, pending task size, @ljohnson09 said she recalled @naglepuff suggesting a model where this button makes a pop up where the user can input their question into a form & it would email the support email.

**Comment by mslarae13** [comment]
@naglepuff @marySalvi 
@shreddd approved this issue and a couple others for priority between now & early May.
Can you comment on when you can start this & how many sprints will be needed to complete? And I'll update the target dates.

**Comment by naglepuff** [comment]
The time needed for this task depends on the scope.

If we want to add a simple modal that directs users to the support email address, that could be accomplished in ~4 hours. If we wanted to add discussion to how users could access this modal (by clicking a button? where does the button go? what does it say?), we could ask @faiza-a for input, and add another ~4 hours to the task, so 1 sprint.

If we want to create a form that allows users to send emails, that would be a much bigger ask and has more uncertainty (at least from my end). As long as we're able to easily connect to the SMTP server for the given support email, this shouldn't be that bad, but there may also be security considerations that require some due diligence. i.e. we'd want to prevent users from being able to spam the email endpoint. This would be closer to 20-30 hours and I think 2-3 sprints worth of work. This is a very cautious estimate.

We could also implement a system where instead of emailing feedback we store it in postgres and establish some way for project team members to read it. This would require additional designs and would also take 20-30 hours/2-3 sprints.

**Comment by ljohnson09** [comment]
@mslarae13 I think a simple modal w/ support email address would be fine, but we may want input from Faiza for where it should go. Probably should have some sort of instructions for the user to let them know what info we need from them to be able to help them! @jkelliher-github may have more insights about the CRM/ticketing system (I think it's on backlog for now), and how that could be integrated with this.

**Comment by faiza-a** [comment]
Here is some idea for [Support button](https://www.figma.com/design/KUtfSqxhYCn334xkoh2CBr/Submission-Portal?node-id=1982-17&t=XsB9Eh98G5WWTprn-0). Initially keep only options that are available and later add other buttons in the menu.
Let me know if this works.
<img width="959" alt="support button" src="https://github.com/microbiomedata/user_research/assets/61198087/45609721-4cfb-4d1e-b5be-c3ed131f6ead">

**Comment by ssarrafan** [comment]
Added this to this sprint for Mary per discussions at the infra sync meeting today.  
@ljohnson09 agrees with Faiza's suggestions

**Comment by ssarrafan** [comment]
Mary did a demo of part of this yesterday but it looks like she's still working on it.  Moving to next sprint
@marySalvi

**Comment by ssarrafan** [comment]
@marySalvi can this be closed yet?

**Comment by mslarae13** [comment]
I haven't tested yet (not deployed on dev). So I don't think it's done? but may be by COB today or Monday?

**Comment by mslarae13** [comment]
@marySalvi can you link your PR?

**Comment by naglepuff** [comment]
See https://github.com/microbiomedata/nmdc-server/pull/1292. I have to head out early today so most likely Monday unless someone else can take over code review

**Comment by ssarrafan** [comment]
Ok moving to next sprint

**Comment by mslarae13** [comment]
Looks great Mary!!
@ljohnson09 please check out on the -dev site!

**Comment by ljohnson09** [comment]
From what Montana showed me via screenshots, it looks perfect! I'm not able to get the bottom three buttons to work on my end. I'm using Chrome and get no response at all. When I test in Firefox it redirects back to Chrome but just back to the tab I was on, does not open an email draft. It may be a LANL block on popups or something though!

**Comment by marySalvi** [comment]
> From what Montana showed me via screenshots, it looks perfect! I'm not able to get the bottom three buttons to work on my end. I'm using Chrome and get no response at all. When I test in Firefox it redirects back to Chrome but just back to the tab I was on, does not open an email draft. It may be a LANL block on popups or something though!

My initial thought is that perhaps you have an unconventional default e-mail setup or that this action is specifically blocked. The Chrome redirection is making me think the latter. I will reach out on slack to get more details/meetup.

**Comment by mslarae13** [comment]
If others could please test this that would be great!
Other email tools, browsers, and OS

Go to the submission portal -dev site & click the options that are available in the new purple "support" side button.

@lamccue @bmeluch @brynnz22 @eecavanna @emileyfadrosh @ssarrafan @turbomam @SamuelPurvine

**Comment by ljohnson09** [comment]
Tagging @frodriguez16 @jkelliher-github @kaelanprime to see if it's a LANL block or my computer - Kaelan has set up the outlook desktop app successfully on her computer

**Comment by frodriguez16** [comment]
It worked for me on Outlook (desktop app)!

**Comment by kaelanprime** [comment]
It worked for me on Outlook desktop (and also the Mac mail client when I had to use it to set my default for my Outlook app)!

**Comment by eecavanna** [comment]
I went to https://data-dev.microbiomedata.org/submission/home in Brave Browser on macOS.

FYI: I don't see the "Support" button when I'm not logged in (maybe that's intentional). When I'm logged in, I do see it.

When I click the "Send us a message" button, Brave shows this popup:

![image](https://github.com/user-attachments/assets/d6825e87-b21d-47b5-9daf-a05ed3e1cadb)

When I click "Open Mail," macOS opens the default Mail app (which does not have any email accounts configured in it).

![image](https://github.com/user-attachments/assets/bfe2ced8-5780-4013-946d-d1eb586481db)

Aside from the absence of the "Support" button when I'm not logged in, this all matches my expectations.

**Comment by turbomam** [comment]
Works nicely for me on Ubuntu 22 workstation with Chrome as default browser and Gmail as default mail client/provider

**Comment by bmeluch** [comment]
Works for me
Windows 10 Enterprise, both Chrome v 126.0.6478.183 and Firefox v 128.0, email links open in Outlook desktop app

Not sure if this is intentional but on this page https://microbiomedata.org/contact/ the social links in the blue rectangle aren't actually links? I instinctively went to click on those to no avail. The links at the bottom work fine.

**Comment by ssarrafan** [comment]
It worked for me. 
I tested in Chrome version 126.0.6478.127 and Safari version 16.6.
In both cases I only see the purple support if I'm logged in to ORCiD.  
In both cases it opens a new email for all three options in the Mail app on my Mac laptop running Ventura. 
I would have expected when I went to the "visit our support page" link that those options would also be click-able but they're not.
